market_bucket/images/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, escape, sessions
from flask_login import login_required, current_user
from market_bucket.images.forms import UploadForm, EditCaptionForm, DeleteForm
from market_bucket.helpers.helpers import allowed_file, upload_image
from werkzeug.utils import secure_filename
from market_bucket.images.model import Image, db
import random

images_blueprint = Blueprint('images',
                             __name__,
                             template_folder='templates')


@images_blueprint.route("<id>/new", methods=['GET'])
@login_required
def new(id):
    form = UploadForm()
    return render_template('images/upload.html', form=form)


@images_blueprint.route("<id>/upload", methods=['POST'])
@login_required
def upload(id):
    if int(id) == current_user.id:

        # check there is a file
        form = UploadForm()
        if "user_image" not in request.files:
            flash("No image was uploaded!")
            return render_template('images/upload.html', form=form)

        # grab the photo and caption
        file = request.files["user_image"]
        caption = form.image_caption.data

        # check there is a name
        if file.filename == "":
            flash("Please give your photo a valid name!")
            return render_template('images/upload.html', form=form)

        # check file size
        if len(file.read()) > (2 * 1024 * 1024):
            flash("Please upload a file smaller than 2 MB!")
            return render_template('images/upload.html', form=form)

        # check correct extension and upload if valid
        if file and allowed_file(file.filename):
            file.seek(0)
            serial_filename = f'{current_user.id}.{random.randint(1,100000)}.{file.filename}'
            file.filename = secure_filename(serial_filename)
            upload_image(file)

            new_image = Image(
                user_id=id,
                product_id=1,  #hard coded for testing
                image_name=str(file.filename),
                image_caption=caption
            )

            db.session.add(new_image)
            db.session.commit()
            flash('Product image added successfully!')
            # change redirect destination later
            return redirect(url_for('home', id=current_user.id))
        else:
            flash('Upload a valid image format!')
            return render_template('images/upload.html', form=form)

    return redirect(url_for('home', id=current_user.id))

market_bucket/marketplaces/views.py
from market_bucket.marketplaces.model import Marketplace, db
from flask import redirect, url_for, render_template, Blueprint, flash, request
from flask_login import current_user, login_required
from market_bucket.helpers.lazada_sdk.lazop.base import LazopClient, LazopRequest, LazopResponse
from market_bucket import LAZADA_MARKET_KEY, LAZADA_MARKET_SECRET, LAZADA_REDIRECT_URI, lazada, oauth

marketplaces_blueprint = Blueprint(
    'marketplaces', __name__, template_folder='templates')


@marketplaces_blueprint.route('/check/lazada')
@login_required
def lazada_authorize():
    return lazada.authorize_redirect(LAZADA_REDIRECT_URI, _external=True)


@marketplaces_blueprint.route('/authorize/lazada')
def lazada_authorize_login():
    code = request.args.get('code')
    client = LazopClient("https://auth.lazada.com/rest",
                         LAZADA_MARKET_KEY, LAZADA_MARKET_SECRET)
    api_request = LazopRequest("/auth/token/create")
    api_request.add_api_param("code", code)
    response = client.execute(api_request)
    access_token = response.body.get('access_token')
    refresh_token = response.body.get('refresh_token')
    seller_id = response.body.get('country_user_info')[0].get('seller_id')
    short_code = response.body.get('country_user_info')[0].get('short_code')
    # email = response.body.get('account')
    print(response.body)

    new_marketplace = Marketplace(
        user_id=current_user.id,
        marketplace_name="lazada",
        shop_id=seller_id,
        shop_name=short_code,
        access_token=access_token,
        refresh_token=refresh_token
    )

    db.session.add(new_marketplace)
    db.session.commit()
    flash('Lazada has been added to your omni-marketplace!')
    return redirect(url_for('home'))  # change redirect destination later

# Not authorised yet :(


@marketplaces_blueprint.route('/check/<order>/lazada')
def check_order(order):
    client = LazopClient("https://api.lazada.com.my/rest",
                         LAZADA_MARKET_KEY, LAZADA_MARKET_SECRET)
    request = LazopRequest('/order/get', 'GET')
    request.add_api_param('order_id', str(order))
    response = client.execute(
        request, Marketplace.query.filter(
            Marketplace.user_id == current_user.id, Marketplace.marketplace_name == "lazada").first().access_token)
    print(response)
    print(response.type)
    print(response.body)
    import pdb
    pdb.set_trace()
    return redirect(url_for('home'))  # change redirect destination later

market_bucket/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, escape, sessions
from market_bucket.users.forms import SignupForm
from market_bucket.users.model import User, db
from market_bucket.marketplaces.model import Marketplace
from flask_login import login_user, logout_user, login_required, login_url, current_user

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route("/new", methods=['GET'])
def new():
    if current_user.is_authenticated:
        flash('You are already logged in!!')
        return redirect(url_for('home'))  # change redirect destination later
    else:
        form = SignupForm()
        return render_template('users/new.html', form=form)


@users_blueprint.route("/create", methods=['POST'])
def create():
    form = SignupForm(request.form)

    new_user = User(
        store_name=form.store_name.data,
        first_name=form.first_name.data,
        last_name=form.last_name.data,
        email=form.email.data.lower(),
        password=form.password.data
    )

    if len(new_user.validation_errors) > 0:
        return render_template('users/new.html', validation_errors=new_user.validation_errors, form=form)
    else:
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        flash('Account created successfully')
        # change redirect destination later
        return redirect(url_for('home', id=current_user.id))


@users_blueprint.route("<id>/dashboard", methods=['GET'])
@login_required
def dashboard(id):
    return render_template("users/dashboard.html", Marketplace=Marketplace)

market_bucket/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,400" rel="stylesheet">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

  <title>
    {% block title %}
    {% endblock %}
  </title>

  <!-- Bootstrap 4.1.1 -->
  {% assets "css_all" %}
  <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% assets "js_all" %}
  <script type="text/javascript" src="{{ ASSET_URL }}"></script>
  {% endassets %}

  {% block custom_head %}
  {% endblock %}
</head>

<body>

  {% with messages = get_flashed_messages() %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-info fade show alert-dismissible">
          <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
          {{message}}
        </div>
      {% endfor %}
    {% endif %}
  {% endwith %}

  {% block content %}
  {% endblock %}


  {% block custom_js %}
  {% endblock %}
</body>

</html>

market_bucket/templates/home.html
{% extends "_base.html" %}

{% block title %}
Home
{% endblock %}

{% block custom_head %}
{% endblock %}

{% block content %}

<div class="container">
  <h1>Welcome to the one and only store</h1>

  {% if current_user.is_authenticated %}
  <h1>Great job, you signed up, {{current_user.first_name}}. Now What?! ...</h1>
  <a href="{{ url_for('sessions.logout') }}" class="btn btn-primary">Sign out!</a>
  <a href="{{ url_for('images.new', id = current_user.id) }}" class="btn btn-primary">Upload Images!</a>
  <a href="{{ url_for('marketplaces.lazada_authorize') }}" class="btn btn-primary">Lazada!</a>
  {% else %}
  <a href="{{ url_for('users.new') }}" class="btn btn-primary">Sign up!</a>
  <a href="{{ url_for('sessions.new') }}" class="btn btn-primary">Sign in!</a>
  <a href="{{ url_for('sessions.google_authorize') }}" class="btn btn-primary">Sign up/in with google!</a>
  {% endif %}
</div>

{% endblock %}