market_bucket/images/forms.py
from flask_wtf import FlaskForm
from flask_wtf.csrf import CsrfProtect
from wtforms import FileField, PasswordField, SubmitField, TextAreaField


class UploadForm(FlaskForm):
    user_image = FileField('User Image')
    image_caption = TextAreaField('Image Caption')
    submit = SubmitField('Submit')


class EditCaptionForm(FlaskForm):
    image_caption = TextAreaField('Image Caption')
    submit = SubmitField('Submit')


class DeleteForm(FlaskForm):
    submit = SubmitField('Submit')

market_bucket/images/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, escape, sessions
from flask_login import login_required, current_user
from market_bucket.images.forms import UploadForm, EditCaptionForm, DeleteForm
from market_bucket.helpers.helpers import allowed_file, upload_image
from werkzeug.utils import secure_filename
from market_bucket.images.model import Image, db
import random

images_blueprint = Blueprint('images',
                             __name__,
                             template_folder='templates')


@images_blueprint.route("<id>/new", methods=['GET'])
@login_required
def new(id):
    form = UploadForm()
    return render_template('images/upload.html', form=form)


@images_blueprint.route("<id>/upload", methods=['POST'])
@login_required
def upload(id):
    if int(id) == current_user.id:

        # check there is a file
        form = UploadForm()
        if "user_image" not in request.files:
            flash("No image was uploaded!")
            return render_template('images/upload.html', form=form)

        # grab the photo and caption
        file = request.files["user_image"]
        caption = form.image_caption.data

        # check there is a name
        if file.filename == "":
            flash("Please give your photo a valid name!")
            return render_template('images/upload.html', form=form)

        # check file size
        if len(file.read()) > (2 * 1024 * 1024):
            flash("Please upload a file smaller than 2 MB!")
            return render_template('images/upload.html', form=form)

        # check correct extension and upload if valid
        if file and allowed_file(file.filename):
            file.seek(0)
            serial_filename = f'{current_user.id}.{random.randint(1,100000)}.{file.filename}'
            file.filename = secure_filename(serial_filename)
            upload_image(file)

            new_image = Image(
                user_id=id,
                product_id=1,  #hard coded for testing
                image_name=str(file.filename),
                image_caption=caption
            )

            db.session.add(new_image)
            db.session.commit()
            flash('Product image added successfully!')
            # change redirect destination later
            return redirect(url_for('home', id=current_user.id))
        else:
            flash('Upload a valid image format!')
            return render_template('images/upload.html', form=form)

    return redirect(url_for('home', id=current_user.id))

market_bucket/images/templates/images/upload.html
{% extends "_base.html" %}
{% block title %}
Upload Your Images!
{% endblock %}
{% block content %}
<h1>Upload Your Product Images!</h1>


<form class="mb-auto w-100 p-5" action="{{ url_for('images.upload', id= current_user.id) }}" method="POST" enctype="multipart/form-data">
    {{ form.csrf_token }}

    <div class="form-group">
        {{ form.user_image (class='form-control border-top-0 border-left-0 border-right-0
        bg-transparent',placeholder="Upload Your Image") }}
    </div>

    <div class="form-group">
        {{ form.image_caption (class='form-control border-top-0 border-left-0 border-right-0
        bg-transparent',placeholder="Caption (Optional)") }}
    </div>


    <div class="d-flex flex-row mt-3 ml-1">
        {{ form.submit (class='btn btn-dark',value="Upload")}}
    </div>
</form>

{% endblock %}