market_bucket/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.csrf import CsrfProtect
from wtforms import StringField, PasswordField, SubmitField


class SignupForm(FlaskForm):
    first_name = StringField('First Name')
    last_name = StringField('Last Name')
    email = StringField('Email')
    store_name = StringField('Store Name')
    password = PasswordField('Password')
    submit = SubmitField('Submit')

market_bucket/users/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, escape, sessions
from market_bucket.users.forms import SignupForm
from market_bucket.users.model import User, db
from market_bucket.marketplaces.model import Marketplace
from flask_login import login_user, logout_user, login_required, login_url, current_user

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')


@users_blueprint.route("/new", methods=['GET'])
def new():
    if current_user.is_authenticated:
        flash('You are already logged in!!')
        return redirect(url_for('home'))  # change redirect destination later
    else:
        form = SignupForm()
        return render_template('users/new.html', form=form)


@users_blueprint.route("/create", methods=['POST'])
def create():
    form = SignupForm(request.form)

    new_user = User(
        store_name=form.store_name.data,
        first_name=form.first_name.data,
        last_name=form.last_name.data,
        email=form.email.data.lower(),
        password=form.password.data
    )

    if len(new_user.validation_errors) > 0:
        return render_template('users/new.html', validation_errors=new_user.validation_errors, form=form)
    else:
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        flash('Account created successfully')
        # change redirect destination later
        return redirect(url_for('home', id=current_user.id))


@users_blueprint.route("<id>/dashboard", methods=['GET'])
@login_required
def dashboard(id):
    return render_template("users/dashboard.html", Marketplace=Marketplace)

market_bucket/users/templates/users/dashboard.html
{% extends "_base.html" %}
{% block title %}
Dashboard
{% endblock %}

{% block content %}


<a href="{{ url_for('sessions.logout') }}" class="btn btn-primary">Sign out!</a>
<a href="{{ url_for('images.new', id = current_user.id) }}" class="btn btn-primary">Upload Images!</a>
<a href="{{ url_for('marketplaces.check_order', order = 212531555296229) }}" class="btn btn-primary">Check Order!</a>
<a href="{{ url_for('products.new_product', marketplace='lazada') }}" class="btn btn-primary">New Product!</a>
<h1>Great job, you're in, {{current_user.first_name}}. Now What?! ...</h1>

<div class="container h-100">
  <div class="row h-100">
    <!-- CARD SECTION -->
    <div class="card d-inline-block text-center h-50 m-2" style="width: 18rem;">
      <button type="button" class="btn p-0" data-toggle="modal" data-target="#Modal">
        <i class="fas fa-plus fa-7x"></i>
      </button>
      <div class="card-body">
        <h5 class="card-title">Add a marketplace</h5>
        <p class="card-text">Choose the marketplace you would like to add and enter your credentials when prompted</p>
      </div>
    </div>
    <!-- /CARD SECTION -->

    <!-- LAZADA CARD SECTION -->
    {% if Marketplace.query.filter(Marketplace.marketplace_name=="lazada",
    Marketplace.user_id==current_user.id).first() %}
    <div class="card d-inline-block text-center h-50 m-2" style="width: 18rem;">
      <a href="" class="p-0">
        <img class="mb-4" width="250px" src="./../../../static/images/Lazada.jpg" alt="Lazada">
      </a>
      <div class="card-body">
        <h5 class="card-title">Lazada</h5>
        <p class="card-text">Stats</p>
      </div>
    </div>
    {% endif %}
    <!-- / LAZADA CARD SECTION -->

    <!-- Shopee CARD SECTION -->
    {% if Marketplace.query.filter(Marketplace.marketplace_name=="shopee",
    Marketplace.user_id==current_user.id).first() %}
    <div class="card d-inline-block text-center h-50 m-2" style="width: 18rem;">
      <a href="" class="p-0">
        <img width="250px" src="./../../../static/images/shopee.png" alt="Shopee">
      </a>
      <div class="card-body">
        <h5 class="card-title">Shopee</h5>
        <p class="card-text">Stats</p>
      </div>
    </div>
    {% endif %}
    <!-- / Shopee CARD SECTION -->
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLabel">Marketplace List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul style="list-style-type:none">
          <li>
            {% if Marketplace.query.filter(Marketplace.marketplace_name=="lazada",
            Marketplace.user_id==current_user.id).first() %}
            <img height="100px" src="./../../../static/images/Lazada.jpg" alt="Lazada">
            {% else %}
            <a href="{{ url_for('marketplaces.lazada_authorize') }}" class="btn"><img height="100px" src="./../../../static/images/Lazada.jpg"
                alt="Lazada"></a>
            {% endif %}
          </li>
          <hr>
          <li>
            {% if Marketplace.query.filter(Marketplace.marketplace_name=="shopee",
            Marketplace.user_id==current_user.id).first() %}
            <img height="100px" src="./../../../static/images/shopee.png" alt="Shopee">
            {% else %}
            <a href="" class="btn"><img height="100px" src="./../../../static/images/shopee.png" alt="Shopee"></a>
            {% endif %}
          </li>
          <hr>
          <li>
            More marketplaces coming soon...
          </li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- /Modal -->

{% endblock %}

market_bucket/users/templates/users/new.html
{% extends "_base.html" %}
{% block title %}
User Sign-up
{% endblock %}

{% block content %}

{% for error in validation_errors %}
<div class="alert alert-danger fade show alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
  {{error}}
</div>
{% endfor %}

<!-- SIGN UP SECTION -->
<section class="h-100" id="signup-page">
  <div class="container-fluid h-100">
    <div class="row h-100">
      <div class="col-md-7 h-100 d-none d-md-block" id="signup-left-banner">
        <div class="mb-auto mt-3">
          <img src="../../../static/images/logo.png" height="40px" alt="">
        </div>
      </div>
      <div class="col-md-5 h-100 d-flex align-items-start flex-column" id="login-right-banner">
        <div class="mb-auto m-5">
            <h1>Sign Up</h1>
            <p class="mb-0">Hello! Let's get started</p>
        </div>
        <form class="mb-auto w-100 p-5" action="{{ url_for('users.create') }}" method="POST">
          {{ form.csrf_token }}
          <div class="form-group">
            {{ form.first_name (class='form-control border-top-0 border-left-0 border-right-0 bg-transparent',placeholder="First Name")}}
          </div>
          <div class="form-group">
            {{ form.last_name (class='form-control border-top-0 border-left-0 border-right-0 bg-transparent',placeholder="Last Name")}}
          </div>
          <div class="form-group">
            {{ form.email (class='form-control border-top-0 border-left-0 border-right-0 bg-transparent',placeholder="Email")}}
          </div>
          <div class="form-group">
            {{ form.store_name (class='form-control border-top-0 border-left-0 border-right-0 bg-transparent',placeholder="Store Name")}}
          </div>
          <div class="form-group">
            {{ form.password (class='form-control border-top-0 border-left-0 border-right-0 bg-transparent',placeholder="Password")}}
          </div>  
          <div class="d-flex flex-row mt-3 ml-1">
            {{ form.submit (class='btn btn-dark',value="Sign Up")}}
            <a href="{{ url_for('sessions.google_authorize') }}" class="btn btn-primary h-50 ml-1" id="google-button">
              <i class="fab fa-google"></i>
            </a>
          </div>
        </form>
        <div class="mt-auto mx-auto mb-3">
          <small class="text-muted">Already have an account, login 
            <a class="text-muted border-bottom" href="{{url_for('sessions.new')}}">here</a> 
            !
          </small>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /SIGN UP SECTION -->

{% endblock %}